### ISSUE TITLE
C# code in the README snippets

### ISSUE THREAD

**Issue by havanagrawal** [sunnypatel165/31DaysOfRefactoringInJava#1]
The code snippets in the READMEs are in C#, whereas you'd expect them to be in Java.

**Comment by sunnypatel165** [comment]
The idea was to have the pages/content from the original book as it is in the READMEs, and the code in the repo is Java.
You think it makes sense to have Java in README as well?

**Comment by havanagrawal** [comment]
Yeah, coz when I look at just the README, I (a Java guy) won't completely understand or appreciate the problem at hand. The snippets look like gibberish to me, coz' you know, C# 😐

**Comment by sunnypatel165** [comment]
Hmm, makes sense.
Will fix.

**Comment by sunnypatel165** [comment]
Fixed.
