### ISSUE TITLE
Links in ToC of Main README have hard links

### ISSUE THREAD

**Issue by havanagrawal** [sunnypatel165/31DaysOfRefactoringInJava#8]
The links in your table of contents in the main README link directly to your repo. Someone with a fork to your repo cannot use the main README to navigate his own repo.

Specifically, instead of this:
`[Day 1 - Encapsulate Collection](https://github.com/sunnypatel165/31DaysOfRefactoringInJava/tree/master/src/com/sunnypatel/daysofrefactoringjava/day1/encapsulatecollection)`

You need to have
`[Day 1 - Encapsulate Collection](src/com/sunnypatel/daysofrefactoringjava/day1/encapsulatecollection)`

Will send a PR.

**Comment by sunnypatel165** [comment]
Cool, Thanks!
